/*
 * File: app/view/Customer.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VideoShop.view.Customer', {
    extend: 'Ext.window.Window',
    alias: 'widget.vscustomer',

    requires: [
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.toolbar.Paging'
    ],

    height: 484,
    width: 544,
    layout: 'fit',
    title: 'Customer',

    items: [
        {
            xtype: 'form',
            layout: 'fit',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    ui: 'i21-toolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnFind',
                            ui: 'i21-button-toolbar-small',
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Remove'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    bodyCls: 'i21-tab',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Details',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'ctnCustomer',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            margin: 5,
                                            layout: 'form',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtLastName',
                                                    fieldLabel: 'Last Name'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtFirstName',
                                                    fieldLabel: 'First Name'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtMiddleName',
                                                    fieldLabel: 'Middle Name'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtEmail',
                                                    fieldLabel: 'Email'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    itemId: 'dtmDOB',
                                                    fieldLabel: 'Date Of Birth'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtStreet',
                                                    fieldLabel: 'Street'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtCity',
                                                    fieldLabel: 'City'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtProvince',
                                                    fieldLabel: 'Province'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtZipCode',
                                                    fieldLabel: 'Zip Code'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    itemId: 'dtmRegistrationDate',
                                                    fieldLabel: 'Registration Date'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'numMemberBalance',
                                                    fieldLabel: 'Member Balance'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'plnAuditLog',
                            title: 'Audit Log',
                            items: [
                                {
                                    xtype: 'auditlogtree'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});