/*
 * File: app/view/CustomerViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VideoShop.view.CustomerViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.vscustomer',

    config: {
        binding: {
            txtLastName: {
                value: '{current.strLastName}'
            },
            txtFirstName: {
                value: '{current.strFirstName}'
            },
            txtMiddleName: {
                value: '{current.strMiddleName}'
            },
            txtEmail: {
                value: '{current.strEmail}'
            },
            dtmDOB: {
                value: '{current.dtmDateOfBirth}'
            },
            txtStreet: {
                value: '{current.strStreet}'
            },
            txtCity: {
                value: '{current.strCity}'
            },
            txtProvince: {
                value: '{current.strProvince}'
            },
            txtZipCode: {
                value: '{current.strZipCode}'
            },
            dtmRegistrationDate: {
                value: '{current.dtmDRegistrationDate}'
            },
            numMemberBalance: {
                value: '{current.dblMemberBalance}'
            }
        }
    },

    show: function(config) {
        var me = this,
            win = this.getView(),
            action = config && config.action;
        if (action) {
          win.show();
          var context = win.context ? win.context.initialize() : me.setupContext();
          if (action === 'new') {
            context.data.addRecord();
          } else {
            context.data.load({ filters: config.filters });
          }
        }
      },

    setupContext: function() {
      var me = this,
          win = me.getView();
      win.context = Ext.create('iRely.Engine', {
        window: win,
        store: Ext.create('VideoShop.store.Customer', { pageSize: 1 }),
        binding: me.config.binding, 
        enableAudit: true
      });
      return win.context;
    }
});
