/*
 * File: app/view/Movie.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VideoShop.view.Movie', {
    extend: 'Ext.window.Window',
    alias: 'widget.vsmovie',

    requires: [
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Number',
        'Ext.toolbar.Paging'
    ],

    height: 482,
    width: 498,
    layout: 'fit',
    title: 'Movie',

    items: [
        {
            xtype: 'form',
            layout: 'fit',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    ui: 'i21-toolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnFind',
                            ui: 'i21-button-toolbar-small',
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Remove'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: 'Details',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'ctnHeader',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'container',
                                            margin: 5,
                                            layout: 'form',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtMovieName',
                                                    fieldLabel: 'Movie Name'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'numMovieYear',
                                                    fieldLabel: 'Movie Year'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtDirector',
                                                    fieldLabel: 'Director'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtGenre',
                                                    fieldLabel: 'Genre'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtDescription',
                                                    fieldLabel: 'Description'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'numMovieRentalFee',
                                                    fieldLabel: 'Rental Fee'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'plnAuditLog',
                            title: 'Audit Log',
                            items: [
                                {
                                    xtype: 'auditlogtree'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});