/*
 * File: app/view/RentalViewModel.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VideoShop.view.RentalViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.vsrental',

    requires: [
        'VideoShop.store.BufferedCustomer',
        'VideoShop.store.BufferedMovie'
    ],

    stores: {
        bufferedcustomer: { 
            autoLoad: true,
            type: 'vsbufferedcustomer',
            fields: [
                {name: 'intCustomerId'},
                {name: 'strLastName'},
                {name: 'strFirstName'},
                {name: 'strMiddleName'}
            ]
        },
        bufferedmovie: { 
            type: 'vsbufferedmovie',
            fields: [
                {name: 'intMovieId'},
                {name: 'strMovieName'},
                {name: 'intMovieYear'},
                {name: 'dblMovieRentalFee'}
            ]
        }
    }
});