/*
 * File: app/view/Rental.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VideoShop.view.Rental', {
    extend: 'Ext.window.Window',
    alias: 'widget.vsrental',

    requires: [
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing',
        'Ext.toolbar.Paging'
    ],

    autoShow: true,
    height: 466,
    width: 645,
    layout: 'fit',
    title: 'Movie Rental',

    items: [
        {
            xtype: 'form',
            layout: 'fit',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    flex: 1,
                    ui: 'i21-toolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnFind',
                            ui: 'i21-button-toolbar-small',
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Remove'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    bodyCls: 'i21-tab',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Details',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'ctnHeader',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'container',
                                            margin: 5,
                                            layout: 'form',
                                            items: [
                                                {
                                                    xtype: 'gridcombobox',
                                                    columns: [
                                                        {
                                                            dataIndex: 'intCustomerId',
                                                            dataType: 'numeric',
                                                            text: 'Customer ID',
                                                            hidden: true
                                                        },
                                                        {
                                                            dataIndex: 'strLastName',
                                                            dataType: 'string',
                                                            text: 'Customer Last Name',
                                                            flex: 1
                                                        },
                                                        {
                                                            dataIndex: 'strFirstName',
                                                            dataType: 'string',
                                                            text: 'Customer First Name',
                                                            flex: 1
                                                        },
                                                        {
                                                            dataIndex: 'strMiddleName',
                                                            dataType: 'string',
                                                            text: 'Customer Middle Name',
                                                            flex: 1
                                                        }
                                                    ],
                                                    flex: 1,
                                                    itemId: 'cboCustomer',
                                                    fieldLabel: 'Customer Name',
                                                    displayField: 'strLastName',
                                                    valueField: 'intCustomerId'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    flex: 1,
                                                    itemId: 'dtmRentDate',
                                                    fieldLabel: 'Rent Date'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    flex: 1,
                                                    itemId: 'dtmReturnDate',
                                                    fieldLabel: 'Return Date'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'ctnDetails',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'frmadvancesearchgrid',
                                            itemId: 'grdRentMovie',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    itemId: 'colDetailMovie',
                                                    text: 'Movie Selection',
                                                    editor: {
                                                        xtype: 'gridcombobox',
                                                        columns: [
                                                            {
                                                                dataIndex: 'intMovieId',
                                                                dataType: 'numeric',
                                                                text: 'Movie ID',
                                                                hidden: true
                                                            },
                                                            {
                                                                dataIndex: 'strMovieName',
                                                                dataType: 'string',
                                                                text: 'Movie Name',
                                                                flex: 1
                                                            },
                                                            {
                                                                dataIndex: 'intMovieYear',
                                                                dataType: 'int',
                                                                text: 'Movie Name',
                                                                flex: 1
                                                            },
                                                            {
                                                                dataIndex: 'dblMovieRentalFee',
                                                                dataType: 'int',
                                                                text: 'Rental Name',
                                                                flex: 1
                                                            }
                                                        ],
                                                        flex: 1,
                                                        itemId: 'cboMovie',
                                                        displayField: 'strMovieName',
                                                        valueField: 'strMovieName'
                                                    }
                                                }
                                            ],
                                            plugins: [
                                                {
                                                    ptype: 'cellediting',
                                                    clicksToEdit: 1
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            itemId: 'plnAuditLog',
                            layout: 'fit',
                            title: 'Audit Log',
                            items: [
                                {
                                    xtype: 'auditlogtree'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});